-- ============================================================================
-- CoachOS — complete database initialisation
--
-- Generated by scripts/build-schema.sh from supabase/migrations/*.sql.
-- Run this once, top to bottom, in the Supabase SQL editor to set up a
-- fresh project. It is equivalent to applying every migration in order.
--
-- Do NOT edit this file directly — edit the migrations and regenerate.
-- ============================================================================

-- ─────────────────────────────────────────────────────────────────────────
-- source: supabase/migrations/0001_initial_schema.sql
-- ─────────────────────────────────────────────────────────────────────────
-- ============================================================================
-- CoachOS — initial schema
--
-- Design notes:
--  * Money is ALWAYS integer cents. No numeric/float columns for money.
--  * Financial state is DERIVED from charges/payments/credits. There is no
--    stored balance column anywhere, by design.
--  * History is preserved: players are archived/soft-deleted, charges are
--    voided rather than removed, and charge amounts are captured at creation
--    so later rate changes never rewrite the past.
--  * Every coach-owned table carries coach_id and is protected by RLS.
--
-- Safe to re-run: every statement is guarded.
-- ============================================================================

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------- enums ----

do $$
begin
  create type session_type as enum ('private', 'group');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type session_status as enum ('scheduled', 'cancelled');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type attendance_status as enum ('unmarked', 'present', 'absent', 'skipped');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type player_level as enum ('Beginner', 'Intermediate', 'Advanced');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type attendance_window as enum ('Same day', '24 hours', '48 hours', '72 hours');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type ui_theme as enum ('Light', 'Dark');
exception when duplicate_object then null;
end $$;

-- --------------------------------------------------------------- coaches ---

create table if not exists coaches (
  id                uuid primary key default gen_random_uuid(),
  auth_user_id      uuid not null unique references auth.users (id) on delete cascade,
  name              text not null default '',
  email             text not null default '',
  business_name     text not null default '',
  default_rate_cents integer not null default 7000 check (default_rate_cents >= 0),
  attendance_window attendance_window not null default '24 hours',
  theme             ui_theme not null default 'Light',
  onboarded_at      timestamptz,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

create index if not exists coaches_auth_user_id_idx on coaches (auth_user_id);

-- --------------------------------------------------------------- players ---

create table if not exists players (
  id                 uuid primary key default gen_random_uuid(),
  coach_id           uuid not null references coaches (id) on delete cascade,
  name               text not null check (length(btrim(name)) > 0),
  phone              text not null default '',
  email              text not null default '',
  level              player_level not null default 'Beginner',
  -- NULL means "fall back to the coach's default rate".
  default_rate_cents integer check (default_rate_cents is null or default_rate_cents >= 0),
  notes              text not null default '',
  archived           boolean not null default false,
  -- Soft delete: history stays intact and readable.
  deleted_at         timestamptz,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

create index if not exists players_coach_idx on players (coach_id);
create index if not exists players_coach_active_idx on players (coach_id, archived) where deleted_at is null;

-- -------------------------------------------------------------- sessions ---

create table if not exists sessions (
  id                 uuid primary key default gen_random_uuid(),
  coach_id           uuid not null references coaches (id) on delete cascade,
  type               session_type not null,
  name               text not null default '',
  date               date not null,
  -- Minutes from midnight, matching the design's time model.
  start_min          integer not null check (start_min between 0 and 1439),
  duration_min       integer not null check (duration_min between 5 and 480),
  -- Per-player price captured at scheduling time.
  price_cents        integer not null default 0 check (price_cents >= 0),
  is_free            boolean not null default false,
  location           text not null default '',
  capacity           integer check (capacity is null or capacity between 2 and 12),
  status             session_status not null default 'scheduled',
  attendance_skipped boolean not null default false,
  cancelled_at       timestamptz,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),

  -- A free session must never carry a price.
  constraint sessions_free_has_no_price check (not is_free or price_cents = 0),
  -- Private lessons have no capacity; group sessions must have one.
  constraint sessions_capacity_shape check (
    (type = 'private' and capacity is null) or (type = 'group' and capacity is not null)
  )
);

create index if not exists sessions_coach_date_idx on sessions (coach_id, date);
create index if not exists sessions_coach_status_idx on sessions (coach_id, status);

-- ----------------------------------------------------------- enrollments ---

create table if not exists enrollments (
  id         uuid primary key default gen_random_uuid(),
  coach_id   uuid not null references coaches (id) on delete cascade,
  session_id uuid not null references sessions (id) on delete cascade,
  player_id  uuid not null references players (id) on delete restrict,
  attendance attendance_status not null default 'unmarked',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  unique (session_id, player_id)
);

create index if not exists enrollments_coach_idx on enrollments (coach_id);
create index if not exists enrollments_session_idx on enrollments (session_id);
create index if not exists enrollments_player_idx on enrollments (player_id);

-- --------------------------------------------------------------- charges ---

create table if not exists charges (
  id           uuid primary key default gen_random_uuid(),
  coach_id     uuid not null references coaches (id) on delete cascade,
  player_id    uuid not null references players (id) on delete restrict,
  -- NULL for manual/ad-hoc charges.
  session_id   uuid references sessions (id) on delete restrict,
  amount_cents integer not null check (amount_cents > 0),
  due_date     date not null,
  is_manual    boolean not null default false,
  label        text not null default '',
  note         text not null default '',
  -- Voided charges are written off: they owe nothing but remain on record.
  voided_at    timestamptz,
  void_note    text not null default '',
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index if not exists charges_coach_idx on charges (coach_id);
create index if not exists charges_player_idx on charges (player_id);
create index if not exists charges_session_idx on charges (session_id);
create index if not exists charges_coach_due_idx on charges (coach_id, due_date) where voided_at is null;

-- -------------------------------------------------------------- payments ---
-- Money actually received. Revenue is the sum of these — never of charges.

create table if not exists payments (
  id           uuid primary key default gen_random_uuid(),
  coach_id     uuid not null references coaches (id) on delete cascade,
  charge_id    uuid not null references charges (id) on delete cascade,
  amount_cents integer not null check (amount_cents > 0),
  paid_on      date not null,
  note         text not null default '',
  created_at   timestamptz not null default now()
);

create index if not exists payments_coach_idx on payments (coach_id);
create index if not exists payments_charge_idx on payments (charge_id);
create index if not exists payments_coach_paid_on_idx on payments (coach_id, paid_on);

-- --------------------------------------------------------------- credits ---
-- A reduction of an obligation that is NOT money received.

create table if not exists credits (
  id           uuid primary key default gen_random_uuid(),
  coach_id     uuid not null references coaches (id) on delete cascade,
  charge_id    uuid not null references charges (id) on delete cascade,
  amount_cents integer not null check (amount_cents > 0),
  reason       text not null default '',
  created_at   timestamptz not null default now()
);

create index if not exists credits_coach_idx on credits (coach_id);
create index if not exists credits_charge_idx on credits (charge_id);

-- ------------------------------------------------------- updated_at hook ---

create or replace function set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists coaches_updated_at on coaches;
create trigger coaches_updated_at before update on coaches
  for each row execute function set_updated_at();
drop trigger if exists players_updated_at on players;
create trigger players_updated_at before update on players
  for each row execute function set_updated_at();
drop trigger if exists sessions_updated_at on sessions;
create trigger sessions_updated_at before update on sessions
  for each row execute function set_updated_at();
drop trigger if exists enrollments_updated_at on enrollments;
create trigger enrollments_updated_at before update on enrollments
  for each row execute function set_updated_at();
drop trigger if exists charges_updated_at on charges;
create trigger charges_updated_at before update on charges
  for each row execute function set_updated_at();

-- ─────────────────────────────────────────────────────────────────────────
-- source: supabase/migrations/0002_financial_integrity.sql
-- ─────────────────────────────────────────────────────────────────────────
-- ============================================================================
-- CoachOS — financial integrity
--
-- These constraints are the last line of defence for money. They hold even if
-- the application has a bug, a request is replayed, or two devices submit the
-- same "Mark Paid" at the same moment.
--
-- Safe to re-run: every statement is guarded.
-- ============================================================================

-- Total applied (payments + credits) against one charge, computed inside the
-- database. Used by the guard triggers below.
create or replace function charge_applied_cents(p_charge_id uuid)
returns integer
language sql
stable
as $$
  select
    coalesce((select sum(amount_cents) from payments where charge_id = p_charge_id), 0)
    + coalesce((select sum(amount_cents) from credits  where charge_id = p_charge_id), 0);
$$;

-- Reject any payment/credit that would push a charge past its amount, or that
-- targets a written-off charge. Row locking on the parent charge serialises
-- concurrent inserts, so a double-submitted payment is rejected rather than
-- silently doubling the recorded revenue.
create or replace function guard_charge_application()
returns trigger
language plpgsql
as $$
declare
  v_amount integer;
  v_voided timestamptz;
  v_coach  uuid;
  v_applied integer;
begin
  select amount_cents, voided_at, coach_id
    into v_amount, v_voided, v_coach
    from charges
   where id = new.charge_id
   for update;

  if not found then
    raise exception 'Charge % does not exist', new.charge_id
      using errcode = 'foreign_key_violation';
  end if;

  if v_voided is not null then
    raise exception 'Charge % was written off and cannot be settled', new.charge_id
      using errcode = 'check_violation';
  end if;

  -- Defence in depth: the row must belong to the same coach as its charge.
  if new.coach_id is distinct from v_coach then
    raise exception 'Cross-coach financial write rejected'
      using errcode = 'insufficient_privilege';
  end if;

  v_applied := charge_applied_cents(new.charge_id);

  if v_applied + new.amount_cents > v_amount then
    raise exception
      'Applying % cents would exceed the remaining balance on charge %',
      new.amount_cents, new.charge_id
      using errcode = 'check_violation';
  end if;

  return new;
end;
$$;

drop trigger if exists payments_guard on payments;
create trigger payments_guard
  before insert or update on payments
  for each row execute function guard_charge_application();

drop trigger if exists credits_guard on credits;
create trigger credits_guard
  before insert or update on credits
  for each row execute function guard_charge_application();

-- A charge may not be voided while money has already been collected against
-- it — that money really was received and must stay in revenue.
create or replace function guard_charge_void()
returns trigger
language plpgsql
as $$
declare
  v_paid integer;
begin
  if new.voided_at is not null and old.voided_at is null then
    select coalesce(sum(amount_cents), 0) into v_paid
      from payments where charge_id = new.id;
    if v_paid > 0 then
      raise exception 'Charge % has payments recorded and cannot be voided', new.id
        using errcode = 'check_violation';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists charges_void_guard on charges;
create trigger charges_void_guard
  before update on charges
  for each row execute function guard_charge_void();

-- Repricing a charge must never drop it below what has already been applied.
create or replace function guard_charge_amount()
returns trigger
language plpgsql
as $$
declare
  v_applied integer;
begin
  if new.amount_cents is distinct from old.amount_cents then
    v_applied := charge_applied_cents(new.id);
    if new.amount_cents < v_applied then
      raise exception
        'Charge % already has % cents applied; it cannot be repriced to %',
        new.id, v_applied, new.amount_cents
        using errcode = 'check_violation';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists charges_amount_guard on charges;
create trigger charges_amount_guard
  before update on charges
  for each row execute function guard_charge_amount();

-- Enrollments, charges and payments must all belong to the same coach as the
-- parent record they point at. This closes the door on an IDOR that supplied a
-- valid id from another tenant.
create or replace function guard_same_coach()
returns trigger
language plpgsql
as $$
declare
  v_coach uuid;
begin
  if tg_table_name = 'enrollments' then
    select coach_id into v_coach from sessions where id = new.session_id;
    if v_coach is distinct from new.coach_id then
      raise exception 'Session belongs to a different coach'
        using errcode = 'insufficient_privilege';
    end if;
    select coach_id into v_coach from players where id = new.player_id;
    if v_coach is distinct from new.coach_id then
      raise exception 'Player belongs to a different coach'
        using errcode = 'insufficient_privilege';
    end if;

  elsif tg_table_name = 'charges' then
    select coach_id into v_coach from players where id = new.player_id;
    if v_coach is distinct from new.coach_id then
      raise exception 'Player belongs to a different coach'
        using errcode = 'insufficient_privilege';
    end if;
    if new.session_id is not null then
      select coach_id into v_coach from sessions where id = new.session_id;
      if v_coach is distinct from new.coach_id then
        raise exception 'Session belongs to a different coach'
          using errcode = 'insufficient_privilege';
      end if;
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists enrollments_same_coach on enrollments;
create trigger enrollments_same_coach
  before insert or update on enrollments
  for each row execute function guard_same_coach();

drop trigger if exists charges_same_coach on charges;
create trigger charges_same_coach
  before insert or update on charges
  for each row execute function guard_same_coach();

-- ─────────────────────────────────────────────────────────────────────────
-- source: supabase/migrations/0003_rls_policies.sql
-- ─────────────────────────────────────────────────────────────────────────
-- ============================================================================
-- CoachOS — row level security
--
-- Every coach-owned table is readable and writable ONLY by the coach that owns
-- it. Authorization lives here, in the database, not in the frontend and not
-- in the application's query builders. A leaked or guessed row id from another
-- tenant returns nothing.
--
-- Safe to re-run: every statement is guarded.
-- ============================================================================

alter table coaches     enable row level security;
alter table players     enable row level security;
alter table sessions    enable row level security;
alter table enrollments enable row level security;
alter table charges     enable row level security;
alter table payments    enable row level security;
alter table credits     enable row level security;

-- Force RLS even for the table owner, so a misconfigured connection cannot
-- bypass these policies. (The service_role key still bypasses RLS by design;
-- this application never uses it.)
alter table coaches     force row level security;
alter table players     force row level security;
alter table sessions    force row level security;
alter table enrollments force row level security;
alter table charges     force row level security;
alter table payments    force row level security;
alter table credits     force row level security;

-- The coach row belonging to the current authenticated user.
create or replace function current_coach_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select id from coaches where auth_user_id = auth.uid();
$$;

revoke all on function current_coach_id() from public;
grant execute on function current_coach_id() to authenticated;

-- ---------------------------------------------------------------- coaches --

drop policy if exists coaches_select_own on coaches;
create policy coaches_select_own on coaches
  for select using (auth_user_id = auth.uid());

drop policy if exists coaches_insert_own on coaches;
create policy coaches_insert_own on coaches
  for insert with check (auth_user_id = auth.uid());

drop policy if exists coaches_update_own on coaches;
create policy coaches_update_own on coaches
  for update using (auth_user_id = auth.uid())
  with check (auth_user_id = auth.uid());

-- Deleting a coach profile is not an application operation; omit the policy so
-- it is denied by default.

-- ------------------------------------------------- coach-owned data tables --
-- Each table gets the same shape: you may touch a row only when its coach_id
-- resolves to your own coach record.

drop policy if exists players_all_own on players;
create policy players_all_own on players
  for all using (coach_id = current_coach_id())
  with check (coach_id = current_coach_id());

drop policy if exists sessions_all_own on sessions;
create policy sessions_all_own on sessions
  for all using (coach_id = current_coach_id())
  with check (coach_id = current_coach_id());

drop policy if exists enrollments_all_own on enrollments;
create policy enrollments_all_own on enrollments
  for all using (coach_id = current_coach_id())
  with check (coach_id = current_coach_id());

drop policy if exists charges_all_own on charges;
create policy charges_all_own on charges
  for all using (coach_id = current_coach_id())
  with check (coach_id = current_coach_id());

drop policy if exists payments_all_own on payments;
create policy payments_all_own on payments
  for all using (coach_id = current_coach_id())
  with check (coach_id = current_coach_id());

drop policy if exists credits_all_own on credits;
create policy credits_all_own on credits
  for all using (coach_id = current_coach_id())
  with check (coach_id = current_coach_id());

-- Anonymous visitors get nothing at all.
revoke all on all tables in schema public from anon;

grant select, insert, update, delete on
  coaches, players, sessions, enrollments, charges, payments, credits
to authenticated;

-- ─────────────────────────────────────────────────────────────────────────
-- source: supabase/migrations/0004_new_coach_bootstrap.sql
-- ─────────────────────────────────────────────────────────────────────────
-- ============================================================================
-- CoachOS — create a coach profile automatically on signup.
--
-- Without this, the first request after signup has an authenticated user but
-- no coach row, and current_coach_id() returns NULL (which RLS reads as "no
-- access to anything").
--
-- Safe to re-run: every statement is guarded.
-- ============================================================================

create or replace function handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.coaches (auth_user_id, name, email)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'name', ''),
    coalesce(new.email, '')
  )
  on conflict (auth_user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function handle_new_auth_user();

-- ─────────────────────────────────────────────────────────────────────────
-- source: supabase/migrations/0005_coach_timezone.sql
-- ─────────────────────────────────────────────────────────────────────────
-- ============================================================================
-- CoachOS — per-coach timezone
--
-- The application server runs in UTC. Without a per-coach zone, "today",
-- "has this session ended?" and every overdue calculation are wrong for any
-- coach not on UTC — an evening session rolls into tomorrow mid-session.
--
-- Existing rows default to UTC, which is the previous (incorrect but stable)
-- behaviour; coaches set their real zone at onboarding or in Settings.
--
-- Safe to re-run: every statement is guarded.
-- ============================================================================

alter table coaches
  add column if not exists timezone text not null default 'UTC';

comment on column coaches.timezone is
  'IANA timezone name, e.g. America/Los_Angeles. All calendar decisions for this coach are made in this zone.';

-- Cheap sanity guard: an IANA name, not free text. Full validation happens in
-- the application via Intl, which knows the current tz database.
do $$
begin
  alter table coaches
    add constraint coaches_timezone_shape
    check (timezone = 'UTC' or timezone ~ '^[A-Za-z_]+/[A-Za-z0-9_+\-/]+$');
exception
  when duplicate_object then null;
end $$;

