#!/usr/bin/env bash
# Regenerates supabase/schema.sql from the ordered migration files.
set -euo pipefail
cd "$(dirname "$0")/.."
{
  echo "-- ============================================================================"
  echo "-- CoachOS — complete database initialisation"
  echo "--"
  echo "-- Generated by scripts/build-schema.sh from supabase/migrations/*.sql."
  echo "-- Run this once, top to bottom, in the Supabase SQL editor to set up a"
  echo "-- fresh project. It is equivalent to applying every migration in order."
  echo "--"
  echo "-- Do NOT edit this file directly — edit the migrations and regenerate."
  echo "-- ============================================================================"
  echo
  for f in supabase/migrations/*.sql; do
    echo "-- ─────────────────────────────────────────────────────────────────────────"
    echo "-- source: $f"
    echo "-- ─────────────────────────────────────────────────────────────────────────"
    cat "$f"
    echo
  done
} > supabase/schema.sql
echo "wrote supabase/schema.sql"
